### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by carlesandres**

### CODE REVIEW

**Review by alevito — APPROVED** [review]
:+1:

**Comment by alevito** [comment]
@fenglish do you agree to update the codeowners as specified in the PR?

**Comment by fenglish** [comment]
@alevito Yes, I agree this 120%. Thank you for doing this, @carlesandres!

**Comment by carlesandres** [comment]
Thanks @fenglish ! We need your approval, please 😉

**Review by fenglish — APPROVED** [review]

**Pull request merged**
